version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_APP_URL
        - NEXT_PUBLIC_STORAGE_STRATEGY
        - NEXT_PUBLIC_ENABLE_API_DEBUG
        - NEXT_PUBLIC_ENABLE_NOTIFICATION_DEBUG
        - NEXT_PUBLIC_API_BASE_URL
        - NEXT_PUBLIC_USE_MOCK_API
        - NEXT_PUBLIC_FIREBASE_API_KEY
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        - NEXT_PUBLIC_FIREBASE_APP_ID
        - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        - NEXT_PUBLIC_FIREBASE_VAPID_KEY
        - STRIPE_SECRET_KEY
        - MONGO_URI
        - JWT_SECRET
    container_name: logatech-net

    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./storage:/app/storage
    networks:
      - coolify

networks:
  coolify:
    external: true
